
print((chr(72))+(chr(101))+(chr(101))+(chr(101))+(chr(101))+(chr(101))+(chr(101))+(chr(76))+(chr(76))+(chr(111)),"",(chr(87))+(chr(111))+(chr(114))+(chr(76))+(chr(100)))
print((chr(72))+(chr(101))+(chr(76))+(chr(76)))
print((chr(72))+(chr(76))+(chr(111))+(chr(100))+(chr(100))+(chr(100))+(chr(100))+(chr(100))+(chr(100))+(chr(100)))
print((chr(111))+(chr(76))+(chr(76))+(chr(101))+(chr(72)))
print(((chr(87))+(chr(111))+(chr(114))+(chr(76))+(chr(100))))
print((chr(72))+(chr(101))+(chr(76))+(chr(76))+(chr(111))+(chr(111))+(chr(111))+(chr(111))+(chr(111))+(chr(111))+(chr(111)))