
name = str(input())


math = int(input())
science = int(input())
art = int(input())
PE = int(input())
literature = int(input())


math = math + 2
science = science + 2
art = art + 2
PE = PE + 2
literature = literature + 2

print("---------------------")

print(f'math   : {math}')
print(f'science : {science}')
print(f'art  : {art}')
print(f'PE    : {PE}')
print(f'literature : {literature}')
print(f'scores: [{math}, {science}, {art} ,{PE}, {literature}]')    

        