import math
import numbers
from re import A
from unicodedata import name

name = str(input())

math = int(input())
science = int(input())
art = int(input())
PE = int(input())
literature = int(input())

print(f'math   : {math}')
print(f'science : {science}')
print(f'art  : {art}')
print(f'PE    : {PE}')
print(f'literature : {literature}')
print(f'scores: [{math}, {science}, {art} ,{PE}, {literature}]')


